version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  header: '![](toolchain.svg?localize)'
  icon: secure-lock-kubernetes.svg
  required:
    - repo
  info:
    git url: >
      "[" + $env.repository + "]" +
        "(" + $env.repository + ")"
    git branch: >
      "[" + $env.branch + "]" +
        "(" + $env.repository +
          "/tree/" + $env.branch + ")"
toolchain:
  name: 'Tekton-Toolchain-Trigger-Props-extra-{{timestamp}}'
  template:
    getting_started:
      $ref: "#/messages/template.gettingStarted" 
services:
  repo:
    service_id: githubpublic
    parameters:
      repo_url: 'https://github.com/idsb3t2/KEEP-pipeline-tests-resources'
      type: link
      has_issues: false
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: 'Tekton-Github-Trigger-Props-extra-{{timestamp}}'
      type: tekton
      ui-pipeline: true
      configuration:
        content:
          $text: tekton.yaml
        env:
          GIT_REPO: repo
          REVISION: tekton-samples_master
        execute: true
form:
  pipeline:
    parameters:
      app-name: '{{services.build.parameters.name}}'
      prod-cluster-namespace: prod
    schema:
      $ref: deploy.json
